# Numpy

In [5]:
import numpy as np
data = np.array([[1, 2], [3, 4], [5, 6]])
print(type(data))
print(data)
print(data.ndim,)
print(data.shape)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [21]:
A_I=np.array([1, 2, 3], dtype=np.int)
A_F=np.array([1, 2, 3], dtype=np.float)
A_C=np.array([1, 2+1j, 3j], dtype=np.complex)
print(A_I)
print(A_F)
print(A_C)

[1 2 3]
[1. 2. 3.]
[1.+0.j 2.+1.j 0.+3.j]


In [24]:
SQRT_I=np.sqrt(A_I)
SQRT_F=np.sqrt(A_F)
SQRT_C=np.sqrt(A_C)
print(SQRT_I)
print(SQRT_F)
print(SQRT_C)

[1.         1.41421356 1.73205081]
[1.         1.41421356 1.73205081]
[1.        +0.j         1.45534669+0.34356075j 1.22474487+1.22474487j]


In [25]:
print(SQRT_C.real)
print(SQRT_C.imag)

[1.         1.45534669 1.22474487]
[0.         0.34356075 1.22474487]


In [26]:
x = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]], dtype=np.int64)
print(x.shape)

(2, 5)


In [32]:
print(np.zeros((2,3)))
print(np.zeros(5))


[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]


In [33]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
x=5.1*np.ones((2,3))
print(x)

[[5.1 5.1 5.1]
 [5.1 5.1 5.1]]


In [37]:
print(np.linspace(1,10,10))
print(np.linspace(0,1,10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [38]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


In [39]:
print((X + 2*Y) ** 2)

[[25 16  9]
 [ 1  0  1]
 [ 9 16 25]]


# Matrix

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.eye(5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [48]:
np.diag(np.linspace(0,1,5))

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

### lambda
Fill the array with values of a function. For this we use the lambda operator

In [49]:
f = lambda m,n: n*(m+1)
A = np.fromfunction(f, (6, 6), dtype=int)
print(A)

[[ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]
 [ 0  6 12 18 24 30]]


In [59]:
print(A[0,])  #row 1
print(A[:,0])  #col 1
print(A[-1,:]) # last row

[0 1 2 3 4 5]
[0 0 0 0 0 0]
[ 0  6 12 18 24 30]


In [61]:
a=np.linspace(1,12,12,dtype=int)
np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
x=np.linspace(0,2*np.pi,3)
print(x)

y=np.sin(np.pi*x)
print(y)

print(np.round(y,decimals=3))

[0.         3.14159265 6.28318531]
[ 0.         -0.43030122  0.77685322]
[ 0.    -0.43   0.777]


In [72]:
print(np.mean(y))
print(np.std(y))
print(np.var(y))
print(y<=0)

0.11551733420528199
0.49954222333176335
0.2495424328912413
[ True  True False]


# Matrix with ndarray and reshape


In [73]:
A = np.arange(1, 7).reshape(2, 3)
print(A)
B = np.arange(1, 7).reshape(3, 2)
print(B)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [101]:
#print(A*B) # It does not work!
AB=np.dot(A,B)
print(AB)
BA=np.dot(B,A)
print(BA)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


# Matrix Class

In [92]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)
print(a)
print(b)

print(type(a))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
<class 'numpy.ndarray'>


In [90]:
A=np.matrix(a)
B=np.matrix(b)
print(A)
print(type(A))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [96]:
print(A*B) # OR print(A @ B)
print(A.I)
print(A.T)
print(A.H)

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [100]:
C = np.matrix('3+2j 1-1j; 8+2j 2-3j')
print(C)
print(C.H)


[[3.+2.j 1.-1.j]
 [8.+2.j 2.-3.j]]
[[3.-2.j 8.-2.j]
 [1.+1.j 2.+3.j]]
