# Solve a Spars matrix


In [46]:
import numpy as np
from scipy.linalg import lu
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
P, L, U = lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.28571429  1.          0.          0.        ]
 [ 0.71428571  0.12        1.          0.        ]
 [ 0.71428571 -0.44       -0.46153846  1.        ]]
[[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]


In [13]:
#?sp.sparse

In [63]:
N=6
diagonals = np.zeros((4, N))   # 3 diagonals
diagonals[0,:] = -1
diagonals[1,:] = 2
diagonals[2,:] = -1
diagonals[3,:] = 4

diagonals

array([[-1., -1., -1., -1., -1., -1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.],
       [-1., -1., -1., -1., -1., -1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.]])

In [66]:
import scipy.sparse as spsp
A = spsp.spdiags(diagonals, [-1,0,1,2], N, N, format='csc')

#print(type(A))
#print(spsp.issparse(A))
print(A.todense())
#print(A)


[[ 2. -1.  4.  0.  0.  0.]
 [-1.  2. -1.  4.  0.  0.]
 [ 0. -1.  2. -1.  4.  0.]
 [ 0.  0. -1.  2. -1.  4.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]


In [67]:
b=np.array([2,4,12,5,7,24])
b

array([ 2,  4, 12,  5,  7, 24])

In [68]:
# Find Solution
from scipy.sparse.linalg import dsolve
x=dsolve.spsolve(A, b, use_umfpack=True)
print(x)


[ -5.89320388  37.59223301  12.84466019 -16.05825243   1.96116505
  12.98058252]


In [69]:
# Test Solution and Error
print(A*x)
print(f"Error: {np.mean(A * x - b)}")  


[ 2.  4. 12.  5.  7. 24.]
Error: -2.9605947323337506e-16
